version: "3.4"
services:
 eureka-server:
  image: eureka-server
  ports:
   - "8761:8761"

 address-service:
  image: address-service
  ports:
   - "8090:8090"
  links:
   - eureka-server
  depends_on:
   - eureka-server

 mobile-service:
  image: mobile-service
  ports:
   - "8089:8089"
  depends_on:
   - eureka-server
  links:
   - eureka-server
   
 customer-service:
  image: customer-service
  ports:
   - "8088:8088"
  depends_on:
   - eureka-server
   - mobile-service
   - address-service
  links:
   - eureka-server